name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
      # - { name: Windows VS2019, os: windows-2019  } # deprecated, remove test
        - { name: Windows VS2022, os: windows-2022  }
        - { name: Linux GCC,      os: ubuntu-latest }
        - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS,          os: macos-latest  }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      #run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev
      run: |
          sudo apt-get update
          sudo apt-get install -y \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libfreetype-dev \
          libwayland-dev \
          wayland-protocols \
          libxkbcommon-dev \
          libxinerama-dev

      # libxrandr-dev       <- allows for runtime configuration of display attributes (eg resolution, rotation, etc)
      # libxcursor-dev      <- custom cursor management (eg changing cursor icon)
      # libxi-dev           <- X11 input extension, enables support for for input devices
      # libudev-dev         <- device management
      # libflac-dev         <- FLAC audio support
      # libvorbis-dev       <- .ogg vorbis audio support
      # libgl1-mesa-dev     <- something something OpenGL
      # libegl1-mesa-dev    <- more OpenGL
      # libfreetype-dev     <- text/font rendering
      # #libwayland-dev     <- wayland client library, needed for GLFW
      # #wayland-protocols  <- needed for wayland
      # #libxkbcommon-dev   <- keymap and keyboard layout handling for X11 and wayland
      # libxinerama-dev     <- multi-monitor support

    # -- Windows

    - name: Install Vulkan SDK (Windows)
      if: runner.os == 'Windows'
      uses: humbletim/install-vulkan-sdk@v1.2
      with:
        version: 1.4.335.0
        cache: true

    - name: Debug Vulkan env (Windows)
      if: runner.os == 'Windows'
      run: |
          echo VULKAN_SDK=%VULKAN_SDK%
          dir "%VULKAN_SDK%\Include"
          dir "%VULKAN_SDK%\Lib"

    # -- Linux

    - name: Install Vulkan SDK (Linux)
      if: runner.os == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install -y \
          libvulkan-dev \
          vulkan-utility-libraries-dev \
          spirv-tools \
          vulkan-tools

    # -- MacOS

    - name: Install Vulkan SDK (macOS)
      if: runner.os == 'macOS'
      run: |
          brew install molten-vk

    # -- Checkout

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build ${{matrix.platform.flags}} ${{matrix.config.flags}}

    - name: Build
      run: cmake --build build --config Release