name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
      # - { name: Windows VS2019, os: windows-2019  } # deprecated, remove test
        - { name: Windows VS2022, os: windows-2022  }
        - { name: Linux GCC,      os: ubuntu-latest }
        - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS,          os: macos-latest  }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    # LINUX DEPENDENCIES
    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      #run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev
      run: |
          sudo apt-get update
          sudo apt-get install -y \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          libflac-dev \
          libvorbis-dev \
          libgl1-mesa-dev \
          libegl1-mesa-dev \
          libfreetype-dev \
          libwayland-dev \
          wayland-protocols \
          libxkbcommon-dev \
          libxinerama-dev

      # libxrandr-dev       <- allows for runtime configuration of display attributes (eg resolution, rotation, etc)
      # libxcursor-dev      <- custom cursor management (eg changing cursor icon)
      # libxi-dev           <- X11 input extension, enables support for for input devices
      # libudev-dev         <- device management
      # libflac-dev         <- FLAC audio support
      # libvorbis-dev       <- .ogg vorbis audio support
      # libgl1-mesa-dev     <- something something OpenGL
      # libegl1-mesa-dev    <- more OpenGL
      # libfreetype-dev     <- text/font rendering
      # #libwayland-dev     <- wayland client library, needed for GLFW
      # #wayland-protocols  <- needed for wayland
      # #libxkbcommon-dev   <- keymap and keyboard layout handling for X11 and wayland
      # libxinerama-dev     <- multi-monitor support

    # INSTALL VULKAN PER OS 
    # -- Windows

    - name: Install Vulkan SDK (Windows)
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: 1.4.304.1
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: false
    #- name: configure
    #  run: cmake -B build_win64 -G "Visual Studio 17 2022" -A x64 -DVKVG_RECORDING=false -DVKVG_SVG=false -DGIT_SUBMODULE=true -DBUILD_SHARED_LIBS=OFF
    #- name: build win64
    #  run: cmake --build build_win64 --parallel


    #- name: Prepare Vulkan SDK (Windows)
    #  uses: humbletim/setup-vulkan-sdk@v1.2.1
    #  with:
    #       vulkan-query-version: 1.4.304.1
    #       vulkan-components: Vulkan-Headers, Vulkan-Loader
    #       vulkan-use-cache: true
           

    #- name: Install Vulkan SDK (Windows)
    #  if: runner.os == 'Windows'
    #  uses: humbletim/install-vulkan-sdk@v1.2
    #  with:
    #    version: 1.4.335.0
    #    cache: true

    - name: Export VULKAN_SDK (Windows)
      if: runner.os == 'Windows'
      run: |
          echo "VULKAN_SDK=$VULKAN_SDK" >> $GITHUB_ENV
      shell: bash

    # -- Linux

    - name: Install Vulkan SDK (Linux)
      if: runner.os == 'Linux'
      run: |
          sudo apt-get update
          sudo apt-get install -y \
          libvulkan-dev \
          vulkan-utility-libraries-dev \
          spirv-tools \
          vulkan-tools

    # -- Mac

    - name: Install Vulkan SDK (macOS)
      if: runner.os == 'macOS'
      run: |
          brew install molten-vk

    # CHECKOUT and BUILD

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure and Build (Windows)
      if: runner.os == 'Windows'
      run: |
        # Pass the environment variable value directly to CMake using -DVULKAN_SDK
        SDK_PATH="$VULKAN_SDK"

        cmake -B build ${{matrix.platform.flags}} ${{matrix.config.flags}}
        -DVULKAN_SDK="$SDK_PATH" \
        -DVulkan_INCLUDE_DIR="$SDK_PATH/Include" \
        -DVulkan_LIBRARY="$SDK_PATH/Lib/vulkan-1.lib"
        cmake --build build --config Release --debug-find
      shell: bash

    - name: Configure (Other)
      if: runner.os != 'Windows'
      run: cmake -B build ${{matrix.platform.flags}} ${{matrix.config.flags}}
      #--debug-find

    - name: Build (Other)
      if: runner.os != 'Windows'
      run: cmake --build build --config Release
      #--debug-find